# Generated by Django 5.0.7 on 2024-07-24 11:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_review'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='alive',
        ),
        migrations.RemoveField(
            model_name='task',
            name='cap_bac',
        ),
        migrations.RemoveField(
            model_name='task',
            name='date_of_die',
        ),
        migrations.AddField(
            model_name='task',
            name='content',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='date_posted',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='user',
            field=models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='review',
        ),
    ]
